// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.25.0
// 	protoc        v3.6.1
// source: otp/otp.proto

package otp

import (
	common "github.com/Zzocker/bl-proto-go/common"
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type GetOTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailID string `protobuf:"bytes,1,opt,name=EmailID,proto3" json:"EmailID,omitempty"`
}

func (x *GetOTPRequest) Reset() {
	*x = GetOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otp_otp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTPRequest) ProtoMessage() {}

func (x *GetOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTPRequest.ProtoReflect.Descriptor instead.
func (*GetOTPRequest) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{0}
}

func (x *GetOTPRequest) GetEmailID() string {
	if x != nil {
		return x.EmailID
	}
	return ""
}

type VerifyOTPRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EmailID string `protobuf:"bytes,1,opt,name=EmailID,proto3" json:"EmailID,omitempty"`
	OTP     int32  `protobuf:"varint,2,opt,name=OTP,proto3" json:"OTP,omitempty"`
}

func (x *VerifyOTPRequest) Reset() {
	*x = VerifyOTPRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otp_otp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyOTPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPRequest) ProtoMessage() {}

func (x *VerifyOTPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPRequest.ProtoReflect.Descriptor instead.
func (*VerifyOTPRequest) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyOTPRequest) GetEmailID() string {
	if x != nil {
		return x.EmailID
	}
	return ""
}

func (x *VerifyOTPRequest) GetOTP() int32 {
	if x != nil {
		return x.OTP
	}
	return 0
}

type GetOTPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *common.Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
}

func (x *GetOTPResponse) Reset() {
	*x = GetOTPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otp_otp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetOTPResponse) ProtoMessage() {}

func (x *GetOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetOTPResponse.ProtoReflect.Descriptor instead.
func (*GetOTPResponse) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{2}
}

func (x *GetOTPResponse) GetHeader() *common.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

type VerifyOTPResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *common.Header `protobuf:"bytes,1,opt,name=Header,proto3" json:"Header,omitempty"`
}

func (x *VerifyOTPResponse) Reset() {
	*x = VerifyOTPResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_otp_otp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *VerifyOTPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyOTPResponse) ProtoMessage() {}

func (x *VerifyOTPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_otp_otp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyOTPResponse.ProtoReflect.Descriptor instead.
func (*VerifyOTPResponse) Descriptor() ([]byte, []int) {
	return file_otp_otp_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyOTPResponse) GetHeader() *common.Header {
	if x != nil {
		return x.Header
	}
	return nil
}

var File_otp_otp_proto protoreflect.FileDescriptor

var file_otp_otp_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x6f, 0x74, 0x70, 0x2f, 0x6f, 0x74, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x03, 0x6f, 0x74, 0x70, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x29, 0x0a, 0x0d, 0x47, 0x65, 0x74,
	0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6d,
	0x61, 0x69, 0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6d, 0x61,
	0x69, 0x6c, 0x49, 0x44, 0x22, 0x3e, 0x0a, 0x10, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x54,
	0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x45, 0x6d, 0x61, 0x69,
	0x6c, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x45, 0x6d, 0x61, 0x69, 0x6c,
	0x49, 0x44, 0x12, 0x10, 0x0a, 0x03, 0x4f, 0x54, 0x50, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x4f, 0x54, 0x50, 0x22, 0x38, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4f, 0x54, 0x50, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x3b,
	0x0a, 0x11, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x32, 0x7d, 0x0a, 0x0b, 0x4f,
	0x54, 0x50, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x12, 0x32, 0x0a, 0x07, 0x53, 0x65,
	0x6e, 0x64, 0x4f, 0x54, 0x50, 0x12, 0x12, 0x2e, 0x6f, 0x74, 0x70, 0x2e, 0x47, 0x65, 0x74, 0x4f,
	0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x6f, 0x74, 0x70, 0x2e,
	0x47, 0x65, 0x74, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3a,
	0x0a, 0x09, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x54, 0x50, 0x12, 0x15, 0x2e, 0x6f, 0x74,
	0x70, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f, 0x54, 0x50, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x16, 0x2e, 0x6f, 0x74, 0x70, 0x2e, 0x56, 0x65, 0x72, 0x69, 0x66, 0x79, 0x4f,
	0x54, 0x50, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x24, 0x5a, 0x22, 0x67, 0x69,
	0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x5a, 0x7a, 0x6f, 0x63, 0x6b, 0x65, 0x72,
	0x2f, 0x62, 0x6c, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x2d, 0x67, 0x6f, 0x2f, 0x6f, 0x74, 0x70,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_otp_otp_proto_rawDescOnce sync.Once
	file_otp_otp_proto_rawDescData = file_otp_otp_proto_rawDesc
)

func file_otp_otp_proto_rawDescGZIP() []byte {
	file_otp_otp_proto_rawDescOnce.Do(func() {
		file_otp_otp_proto_rawDescData = protoimpl.X.CompressGZIP(file_otp_otp_proto_rawDescData)
	})
	return file_otp_otp_proto_rawDescData
}

var file_otp_otp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_otp_otp_proto_goTypes = []interface{}{
	(*GetOTPRequest)(nil),     // 0: otp.GetOTPRequest
	(*VerifyOTPRequest)(nil),  // 1: otp.VerifyOTPRequest
	(*GetOTPResponse)(nil),    // 2: otp.GetOTPResponse
	(*VerifyOTPResponse)(nil), // 3: otp.VerifyOTPResponse
	(*common.Header)(nil),     // 4: common.Header
}
var file_otp_otp_proto_depIdxs = []int32{
	4, // 0: otp.GetOTPResponse.Header:type_name -> common.Header
	4, // 1: otp.VerifyOTPResponse.Header:type_name -> common.Header
	0, // 2: otp.OTPServices.SendOTP:input_type -> otp.GetOTPRequest
	1, // 3: otp.OTPServices.VerifyOTP:input_type -> otp.VerifyOTPRequest
	2, // 4: otp.OTPServices.SendOTP:output_type -> otp.GetOTPResponse
	3, // 5: otp.OTPServices.VerifyOTP:output_type -> otp.VerifyOTPResponse
	4, // [4:6] is the sub-list for method output_type
	2, // [2:4] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_otp_otp_proto_init() }
func file_otp_otp_proto_init() {
	if File_otp_otp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_otp_otp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otp_otp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyOTPRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otp_otp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetOTPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_otp_otp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*VerifyOTPResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_otp_otp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_otp_otp_proto_goTypes,
		DependencyIndexes: file_otp_otp_proto_depIdxs,
		MessageInfos:      file_otp_otp_proto_msgTypes,
	}.Build()
	File_otp_otp_proto = out.File
	file_otp_otp_proto_rawDesc = nil
	file_otp_otp_proto_goTypes = nil
	file_otp_otp_proto_depIdxs = nil
}
