// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package otp

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion7

// OTPServicesClient is the client API for OTPServices service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OTPServicesClient interface {
	SendOTP(ctx context.Context, in *GetOTPRequest, opts ...grpc.CallOption) (*GetOTPResponse, error)
	VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error)
}

type oTPServicesClient struct {
	cc grpc.ClientConnInterface
}

func NewOTPServicesClient(cc grpc.ClientConnInterface) OTPServicesClient {
	return &oTPServicesClient{cc}
}

func (c *oTPServicesClient) SendOTP(ctx context.Context, in *GetOTPRequest, opts ...grpc.CallOption) (*GetOTPResponse, error) {
	out := new(GetOTPResponse)
	err := c.cc.Invoke(ctx, "/otp.OTPServices/SendOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *oTPServicesClient) VerifyOTP(ctx context.Context, in *VerifyOTPRequest, opts ...grpc.CallOption) (*VerifyOTPResponse, error) {
	out := new(VerifyOTPResponse)
	err := c.cc.Invoke(ctx, "/otp.OTPServices/VerifyOTP", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OTPServicesServer is the server API for OTPServices service.
// All implementations must embed UnimplementedOTPServicesServer
// for forward compatibility
type OTPServicesServer interface {
	SendOTP(context.Context, *GetOTPRequest) (*GetOTPResponse, error)
	VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error)
	mustEmbedUnimplementedOTPServicesServer()
}

// UnimplementedOTPServicesServer must be embedded to have forward compatible implementations.
type UnimplementedOTPServicesServer struct {
}

func (UnimplementedOTPServicesServer) SendOTP(context.Context, *GetOTPRequest) (*GetOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendOTP not implemented")
}
func (UnimplementedOTPServicesServer) VerifyOTP(context.Context, *VerifyOTPRequest) (*VerifyOTPResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method VerifyOTP not implemented")
}
func (UnimplementedOTPServicesServer) mustEmbedUnimplementedOTPServicesServer() {}

// UnsafeOTPServicesServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OTPServicesServer will
// result in compilation errors.
type UnsafeOTPServicesServer interface {
	mustEmbedUnimplementedOTPServicesServer()
}

func RegisterOTPServicesServer(s grpc.ServiceRegistrar, srv OTPServicesServer) {
	s.RegisterService(&OTPServices_ServiceDesc, srv)
}

func _OTPServices_SendOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServicesServer).SendOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.OTPServices/SendOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServicesServer).SendOTP(ctx, req.(*GetOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OTPServices_VerifyOTP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VerifyOTPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OTPServicesServer).VerifyOTP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/otp.OTPServices/VerifyOTP",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OTPServicesServer).VerifyOTP(ctx, req.(*VerifyOTPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OTPServices_ServiceDesc is the grpc.ServiceDesc for OTPServices service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OTPServices_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "otp.OTPServices",
	HandlerType: (*OTPServicesServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendOTP",
			Handler:    _OTPServices_SendOTP_Handler,
		},
		{
			MethodName: "VerifyOTP",
			Handler:    _OTPServices_VerifyOTP_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "otp/otp.proto",
}
